Add ADR-0022 - Integration Quality Scale
home-assistant/architecture pull request #1162
Opened 2024-10-22 12:26 UTC by joostlek

Add ADR-0022 - Integration Quality Scale

2024-10-22 17:50 UTC, MartinHjelmare requested changes
Try to shorten the text down. It's too much repetition and essay-style.

2024-10-22 17:50 UTC, MartinHjelmare commented on adr/0022-integration-quality-scale.md
> +🥈 Silver: Enhanced reliability and robustness of the integration, ensuring a solid runtime experience. The integration handles errors correctly, including authentication errors and offline devices. T
```suggestion
🥈 Silver: Enhanced reliability and robustness of the integration, ensuring a solid runtime experience. The integration handles errors correctly, including authentication errors and offline devices. The documentation provides more information on what the integration provides. The integration has one or more code owners who help to maintain the integration and ensure this runtime experience lasts.
```

2024-10-22 17:50 UTC, MartinHjelmare commented on adr/0022-integration-quality-scale.md
> +🥇 Gold: The gold standard in delivering the best possible user experience with advanced features and comprehensive support. They are fully featured, user-friendly, and accessible to a wider audience.
```suggestion
🥇 Gold: The gold standard in delivering the best possible user experience with advanced features and comprehensive support. The integration is fully featured, user-friendly, and accessible to a wider audience. It is fully translated, capable of discovering its devices, providing device updates through Home Assistant, and has extensive documentation with examples, use cases, and troubleshooting. The integration provides means for debugging issues and can be fully adjusted through the UI.
```

2024-10-22 17:50 UTC, MartinHjelmare commented on adr/0022-integration-quality-scale.md
> +🏠 Internal: This is an integration used internally by Home Assistant to provide basic components and building blocks for the core program of Home Assistant or for other integrations to built on. The
```suggestion
🏠 Internal: This is an integration used internally by Home Assistant to provide basic components and building blocks for the core program of Home Assistant or for other integrations to build on. The Home Assistant project maintains integrations of this level.
```

2024-10-22 17:50 UTC, MartinHjelmare commented on adr/0022-integration-quality-scale.md
> +Home Assistant integration quality scale has four differentiated tiers to which integration can be graded: 🥉 Bronze, 🥈 Silver, 🥇 Gold, and 🏆 Platinum.
```suggestion
Home Assistant integration quality scale has four differentiated tiers to which an integration can be graded: 🥉 Bronze, 🥈 Silver, 🥇 Gold, and 🏆 Platinum.
```

2024-10-22 17:50 UTC, MartinHjelmare commented on adr/0022-integration-quality-scale.md
> +The bronze tier is the baseline standard and requirement for all new integrations. It meets the minimum requirements in code quality, functionality, and user experience. It complies with the fundamen
We don't need to repeat the description of the tiers again. Just reference the above text, then simply list the named rules required for each tier.

2024-10-31 15:11 UTC, MartinHjelmare commented on adr/0022-integration-quality-scale.md
> +- An increased pressure on developer documentation to make sure it is up-to-date.
```suggestion
- An increased emphasis on developer documentation to make sure it is up-to-date.
```

2024-11-01 09:08 UTC, MartinHjelmare commented on adr/0022-integration-quality-scale.md
> +- A clear and transparent framework for contributors to understand the quality expectations for their integrations.
```suggestion
The integration quality scale will:
- give a clear and transparent framework for contributors to understand the quality expectations for their integrations.
```

2024-11-01 09:08 UTC, MartinHjelmare commented on adr/0022-integration-quality-scale.md
> +- An increased emphasis on developer documentation to make sure it is up-to-date.
```suggestion
- put pressure on the maintenance of the developer documentation to make sure the documentation is up-to-date.
```

2024-11-01 09:08 UTC, MartinHjelmare commented on adr/0022-integration-quality-scale.md
> +Here is a quick overview of the different tiers in the quality integration scale:
```suggestion
Here is an overview of the different tiers in the quality integration scale:
```

2024-11-01 09:08 UTC, MartinHjelmare commented on adr/0022-integration-quality-scale.md
> +Everything in Home Assistant is extendable using integrations. In fact, Home Assistant uses its own integration logic to extend base functionality. For example, the automation engine of Home Assistan
I'd remove this paragraph. It'd not needed. If wanted put the example in the first paragraph of this section instead.

2024-11-04 10:22 UTC, joostlek commented on adr/0022-integration-quality-scale.md
> +- Provides the tooling and documentation troubleshooting issues.
```suggestion
```

2024-11-05 11:03 UTC, MartinHjelmare commented on adr/0022-integration-quality-scale.md
> +The world of IoT and all technologies used by Home Assistant are changing at a fast pace; not just in terms of what Home Assistant can support or do, but also in terms of the software on which Home A
We already say it's changing fast.
```suggestion
The world of IoT and all technologies used by Home Assistant are changing at a fast pace; not just in terms of what Home Assistant can support or do, but also in terms of the software on which Home Assistant is built. Home Assistant is pioneering the technology in the industry at a fast pace.
```

2024-11-05 11:38 UTC, MartinHjelmare approved these changes

2024-11-05 13:06 UTC, MartinHjelmare commented on adr/0022-integration-quality-scale.md
> +Date: yyyy-mm-dd
Remember to update this before merging.

2024-11-19 16:28 UTC, frenck requested changes
Not sure about the consequence part of the ADR, I think we should link to the developer documentation from here as well.

2024-11-19 16:28 UTC, frenck commented on adr/0022-integration-quality-scale.md
> +#### ❓ No score
```suggestion
#### ❓ No score

```

2024-11-19 16:28 UTC, frenck commented on adr/0022-integration-quality-scale.md
> +#### 🏠 Internal
```suggestion
#### 🏠 Internal

```

2024-11-19 16:28 UTC, frenck commented on adr/0022-integration-quality-scale.md
> +#### 💾 Legacy
```suggestion
#### 💾 Legacy

```

2024-11-19 16:28 UTC, frenck commented on adr/0022-integration-quality-scale.md
> +#### 📦 Custom
```suggestion
#### 📦 Custom

```

2024-11-19 16:28 UTC, frenck commented on adr/0022-integration-quality-scale.md
> +### Adjusting the tier of an integration
```suggestion
### Adjusting the tier of an integration

```

2024-11-19 16:28 UTC, frenck commented on adr/0022-integration-quality-scale.md
> +### Adjustments to rules contained in each tier
```suggestion
### Adjustments to rules contained in each tier

```

2024-11-19 16:39 UTC, joostlek commented on adr/0022-integration-quality-scale.md
> +- put pressure on the maintenance of the developer documentation to make sure the documentation is up-to-date.
```suggestion
- put pressure on the maintenance of the developer documentation to make sure the documentation is up-to-date. These can be found [here](https://developers.home-assistant.io/docs/core/integration-quality-scale/)
```

2024-11-20 17:55 UTC, frenck commented on adr/0022-integration-quality-scale.md
> +Date: yyyy-mm-dd
```suggestion
Date: 2024-11-20
```

2024-11-20 17:55 UTC, frenck approved these changes

2024-11-20 17:55 UTC, merged